
import "./globals.css";
import Providers from './providers'
import Navbarr from "@/components/navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
 
  return (
    <html lang="es" className="dark">
      <body >
        <Providers>
          <Navbarr style={{zIndex:1000}}/>
          {children}
        </Providers>
      </body>
    </html>
  );
}
