import "./globals.css";
import Providers from "./providers";
import "rsuite/dist/rsuite-no-reset.min.css";
import { CustomProvider } from "rsuite";
import { AuthProvider } from "./api/users/route";
export const metadata = {
  title: "Create Note App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, pageProps }) {
  return (
    <html lang="es" className="bg-white-blur">
      <body>
        <Providers>
          <CustomProvider>
            <AuthProvider>{children}</AuthProvider>
          </CustomProvider>
        </Providers>
      </body>
    </html>
  );
}
